baseurl = "https://devcows.github.io/hugo-universal-theme/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Software Engineering Laboratory - NAIST"
theme = "hugo-universal-theme"
themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "News"
    identifier = "menu.news"
    url        = "/news/"
    weight     = 2

[[menu.main]]
    name       = "Publications"
    identifier = "portfolio"
    url        = "/portfolio/"
    weight     = 3

[[menu.main]]
    name       = "Research"
    identifier = "research"
    url        = "/research/"
    weight     = 4

[[menu.main]]
    name       = "Life"
    identifier = "life"
    url        = "/life/"
    weight     = 5

[[menu.main]]
    name       = "Access"
    identifier = "menu.contact"
    url        = "/contact/"
    weight     = 6

[[menu.main]]
    name       = "EN"
    identifier = "en"
    url        = "/en/"
    weight     = 7

[params]
    viewMorePostLink = "/news/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["news"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/graduation-m2-2022-03.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    about_us = "<p>奈良先端科学技術大学院大学</br>先端科学技術研究科 情報科学領域</br>〒630-0192 奈良県生駒市高山町8916-5</p>"
    copyright = "<p>© 2013-2023 © 2013-2023 Software Engineering Laboratory, Graduate School of Information Science, Nara Institute of Science and Technology, All rights reserved.</p>"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "SE Lab"

    logo = "img/logo.png"
    logo_small = "img/logo-selab.png"
    contact_url = "/contact"

[permalinks]
    news = "/news/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.members]
    enable = true
    # All members are defined in their own files. You can find example items
    # at 'exampleSite/data/members'.
    # For more information take a look at the README.
    title = "Graduated Students"
    subtitle = "Software Engineering Laboratory produced hundreds of students, who successfully continued their career in the industry and in the academic field. Many Doctor students work in Japan and abroad. We look forward to collaborate with more researchers and widen our research areas."

[params.collaborations]
    enable = true
    # All collaborations are defined in their own files. You can find example items
    # at 'exampleSite/data/collaborations/'.
    # For more information take a look at the README.
    title = "Our Collaborative Universities"
    subtitle = "We collaborate with various Univesities and Research Centers all over the world"

[params.recent_posts]
    enable = true
    title = "From our news"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[server]
[[server.headers]]
  for = "/*"
    [server.headers.values]
    Access-Control-Allow-Origin = "*"

